config/routes.rb
Rails.application.routes.draw do

 # root 'dashboard#index'
 # get 'logout', to: 'dashboard#logout'

  root 'dashboard#index'
  resources :books
  resources :comments
  resources :summaries
  resources :dashboard

  resources :settings do
    collection do
        get '/smtp', to: 'settings#config_smtp'
    end
  end


end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :relation_book_authors
  has_many :book, through: :relation_book_authors

  def self.search(search)
     where("name LIKE ?", "%#{search.to_s.downcase}%")
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :relation_book_authors
  has_many :authors, through: :relation_book_authors
  
  validates :author, presence: true
  validates :title, presence: true,
             length: { :maximum => 140, :message => "O título deve ter no máximo 140 caracteres."}

  def self.search(search)
     where("title LIKE ?", "%#{search.to_s.downcase}%")
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    #  add_foreign_key :comment, :summary
    belongs_to :user
    belongs_to :summary
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base


end

app/models/loan.rb
class Loan < ActiveRecord::Base
end

app/models/relation_book_author.rb
class RelationBookAuthor < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/summary.rb
class Summary < ActiveRecord::Base
    has_many :comments
    validates :title, presence: true,
                        length: { minimum: 10 }, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts,    dependent: :destroy
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/author_controller.rb
class AuthorsController < ApplicationController

  before_action :set_author, only: [:show, :edit, :update, :destroy]
  def index
    @authors = Author.all
    if params[:search]
    @authors = Author.search(params[:search]).order("created_at DESC")
    else
    @authors = Author.all.order('created_at DESC')
    end
  end

  def show
   @author =  Author.find(params[:id])
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Autor criado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /authors/1
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Autor atualizado com sucesso.' }
      else
        format.html { render :edit }
       end
    end
  end

  # DELETE /authors/1
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Autor excluído com sucesso.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params[:author].permit(:name, :bio )
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  def index
    @books = Book.all
    if params[:search]
    @books = Book.search(params[:search]).order("created_at DESC")
    else
    @books = Book.all.order('created_at DESC')
    end
  end

  def show
   @book =  Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
    @authors = Author.all
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Livro criado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /books/1
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Livro atualizado com sucesso.' }
      else
        format.html { render :edit }
       end
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Livro excluído com sucesso.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params[:book].permit(:title, :author, :description, :release, :language, :publishing_house )
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index

        @seven_days_ago = (Time.zone.now - 7.days).midnight.strftime "%d/%m/%Y"
        @today = Time.now.strftime("%d/%m/%Y")

        @new_books = Book.where('created_at >= ?', Time.zone.now - 7.days).count # count books for a week (07 days)
        @new_books_month = Book.where('created_at >= ?', Time.zone.now - 1.months).count # count books for a month (30 days)

        @total_books = Book.count
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update]
  def index
    @settings = Setting.all
  end

  def show
   @setting =  Setting.find(params[:id])
  end


  def edit
    @setting = Setting.find(params[:id])
  end

  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Configuração atualizada com sucesso.' }
      else
        format.html { render :edit }
       end
    end
  end

  private
    def set_setting
      @setting = Setting.find(params[:id])
    end

    def setting_params
      params[:setting].permit(:name, :title, :domain, :url, :email )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/books/_form.html.erb
<%= form_for(@book, html: { class: "ls-form row" }) do |f| %>

  <fieldset>

    <div class="row">
      <div class="col-md-8">
        <label class="ls-label col-md-6">
        <span class="ls-label-text"><%= f.label :title, "Título" %></span>
        <%= f.text_field :title %>
      </label>
     </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <label class="ls-label col-md-6">
        <span class="ls-label-text"><%= f.label :author, "Autor" %></span>
        <%= f.collection_select :relation_book_authors, @authors, :id, :name, multiple: true %>
      </label>
     </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <label class="ls-label col-md-8">
        <span class="ls-label-text"><%= f.label :description, "Descrição" %></span>
        <%= f.text_area :description %>

      </label>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <label class="ls-label col-md-4">
        <span class="ls-label-text"><%= f.label :release, "Versão" %></span>
               <%= f.text_field :release, :placeholder => 'dd/mm/yyyy' %>
        </label>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <label class="ls-label col-md-4">
        <span class="ls-label-text"><%= f.label :language, "Linguagem" %></span>
        <%= f.text_field :language %>
      </label>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <label class="ls-label col-md-5">
        <span class="ls-label-text"><%= f.label :publishing_house, "Editora" %></span>
        <%= f.text_field :publishing_house %>
      </label>

         <%= f.button  "Salvar", :type => "submit" , class: "ls-btn-primary"%>
         <%= f.submit "Limpar", :type => "reset",  class: "ls-btn-primary" %>
         <%= link_to 'Voltar', books_path, class: "ls-btn-darker" %>
    </div>
    </div>

 </fieldset>

<% end %>

app/views/books/edit.html.erb
<h1 class="ls-title-intro ls-ico-book">Editar livro</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<h1 class="ls-title-intro ls-ico-book">Livros</h1>


<% @books.each do |book| %>

<div class="ls-list">
  <header class="ls-list-header">
    <div class="ls-list-title col-md-9">
      <small><%= link_to book.title, book %></small>
      <%=  book.author %>
    </div>
    <div class="col-md-3 ls-txt-right">
            <%= link_to 'Editar', edit_book_path(book) , class: "ls-btn-primary" %>
    </div>
  </header>
</div>

<% end %>

<div class="ls-pagination-filter ">
     <%= link_to 'Novo Livro', new_book_path(@book) , class: "ls-btn-darker" %>
</div>

app/views/books/new.html.erb
 <h1 class="ls-title-intro ls-ico-book">Criar livro</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<h1 class="ls-title-intro ls-ico-book">Livro</h1>

    <%= render 'shared/notification' %>
<%= form_for(@book, html: { class: "ls-form row" }) do |f| %>
<div class="ls-box">
<div class="row">
  <div class="col-md-12">
    <div class="ls-box">
      <p><strong>Título do Livro</strong></p>
      <p class="ls-break-text"><%= @book.title %></p>
      <hr>
      <p><strong>Autor</strong></p>
      <p class="ls-break-text"><%= @book.author %></p>
      <hr>
      <p><strong>Descrição</strong></p>
      <p class="ls-break-text"><%= @book.description %></p>
      <hr>
      <p><strong>Versão</strong></p>
      <p class="ls-break-text"><%= @book.release.to_formatted_s %></p>

           <hr>
      <p><strong>Linguagem</strong></p>
      <p class="ls-break-text"><%= @book.language %></p>
      <hr>
      <p><strong>Editora</strong></p>
      <p class="ls-break-text"><%= @book.publishing_house %></p>
    </div>
  </div>
</div>
</div>

<%= link_to 'Editar', edit_book_path(@book) , class: "ls-btn-darker" %>
<%= link_to 'Voltar', books_path, class: "ls-btn-darker" %>

<% end %>

app/views/dashboard/index.html.erb
<h1 class="ls-title-intro ls-ico-dashboard">Dashboard</h1>

<%= render 'shared/notification' %>

<div class="ls-box-filter" style="background-color: white; border:0">
  <%= form_tag(books_path, :method => "get", class: "ls-form ls-form-inline ls-float-right", id: "search-form") do %>
    <label class="ls-label" role="search">
      <b class="ls-label-text ls-hidden-accessible">Busca por livro</b>

       <%= text_field_tag :search, params[:search], class: "ls-field", placeholder: "Busca por livro" %>
    </label>
    <div class="ls-actions-btn">
      <input type="submit" value="Buscar" class="ls-btn" title="Buscar">
      <% end %>
    </div>
  </form>
</div>

<div class="ls-box ls-board-box" >
  <header class="ls-info-header"  >
    <h2 class="ls-title-3">Estatísticas de Livros</h2>
    <p class="ls-float-right ls-float-none-xs ls-small-info">Período de <strong> <%=@seven_days_ago%> </strong> de <strong><%=@today%> </strong></p>
  </header>
<div id="sending-stats" class="row">

    <div class="col-sm-6 col-md-3 " >
        <div class="ls-box" style="background-color: white">
           <div class="ls-alert-warning ls-md-space">
               <div class="col-md-2 ls-txt-center">
                 <span class="ls-ico-alone ls-ico-text"></span>
               </div>
              <strong>36</strong>
              <small>Emprestados</small>
           </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-3 " >
        <div class="ls-box" style="background-color: white">
           <div class="ls-alert-success ls-md-space">
               <div class="col-md-2 ls-txt-center">
                 <span class="ls-ico-alone ls-ico-book"></span>
               </div>
              <strong><%= @new_books %> </strong>
              <small>Novos Livros</small>
           </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-3 " >
        <div class="ls-box" style="background-color: white">
           <div class="ls-alert-info ls-md-space">
               <div class="col-md-2 ls-txt-center">
                 <span class="ls-ico-alone ls-ico-docs"></span>
               </div>
              <strong> <%= @total_books %>  </strong>
              <small>Livros cadastrados</small>
           </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-3 " >
        <div class="ls-box" style="background-color: white">
           <div class="ls-alert-danger ls-md-space">
               <div class="col-md-2 ls-txt-center">
                 <span class="ls-ico-alone ls-ico-text2"></span>
               </div>
              <strong>15</strong>
              <small>Em atraso</small>
           </div>
        </div>
    </div>

  </div>
</div>

<div class="ls-box ls-lg-space ls-ico-book ls-ico-bg">
  <h1 class="ls-title-1 ls-color-theme">Cadastre um novo Livro no sistema</h1>
       <%= link_to 'Novo Livro', new_book_path(@book) , class: "ls-btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="ls-theme-light-green">
  <head>

    <title> <%= SECRETS["site"]["title"] %> </title>
    <meta charset="utf-8">
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    "application", SECRETS["locastyle"]["css"], :media => "screen" %>
  <%= javascript_include_tag "application", SECRETS["locastyle"]["js"] %>
  
  </head>
  <body>
    <div class="ls-topbar">

    <div class="ls-notification-topbar">
      <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
        <a href="#" class="ls-ico-user"> Nome do Usuário </a>
        <nav class="ls-dropdown-nav ls-user-menu">
        <ul>
          <li>
          <a href="/logout" class="help-suggestions ico-help-circle hidden-xs"><strong><%= t('report.logout') %></strong></a>
          </li>
        </ul>
        </nav>
      </div>
    </div>


      <span class="ls-show-sidebar ls-ico-menu"></span>
      <!-- Nome do produto/marca -->
      <h1 class="ls-brand-name"><%= link_to SECRETS["site"]["title"], root_path, class:"ls-ico-book"%>  </h1>
    </div>
    <main class="ls-main ">

        <div class="container-fluid">
          <%= yield %>
        </div>

    </main>

  <%= render 'shared/menu' %>
<!-- We recommended use jQuery 1.10 or up -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="http://assets.locaweb.com.br/locastyle/3.8.1/javascripts/locastyle.js" type="text/javascript"></script>


  </body>
</html>

app/views/settings/_form.html.erb
<%= form_for(@setting, html: { class: "ls-form row" }) do |f| %>
  <fieldset>

    <div class="row">
      <div class="col-md-8">
        <label class="ls-label col-md-6">
        <span class="ls-label-text"><%= f.label :name, "Nome do site" %></span>
        <%= f.text_field :name %>
      </label>
     </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <label class="ls-label col-md-6">
        <span class="ls-label-text"><%= f.label :title, "Título" %></span>
        <%= f.text_field :title %>
      </label>
     </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <label class="ls-label col-md-8">
        <span class="ls-label-text"><%= f.label :domain, "Domínio" %></span>
        <%= f.text_field :domain %>
      </label>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <label class="ls-label col-md-4">
        <span class="ls-label-text"><%= f.label :url, "URL" %></span>
        <%= f.text_field :url %>
        </label>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <label class="ls-label col-md-4">
        <span class="ls-label-text"><%= f.label :email, "Email" %></span>
        <%= f.text_field :email %>
        </label>
      </div>
    </div>


    <div class="row">
      <div class="col-md-8">
            <%= f.button  "Salvar", :type => "submit" , class: "ls-btn-primary"%>

         <%= link_to 'Voltar', settings_path, class: "ls-btn-darker" %>
    </div>
    </div>

 </fieldset>

<% end %>

app/views/settings/config_smtp.html.erb
<h1 class="ls-title-intro ls-ico-cog">Dados do Servidor SMTP</h1>
<p>Utilize e gerencie as informações de autenticação do servidor SMTP.</p>
<table class="ls-table ls-table-striped">
  <tbody>
    <tr>
      <td><strong>Usuário: </strong> username</td>
    </tr>
    <tr>
      <td>
        <strong>Senha: </strong>
        <input type="password" maxlength="20" id="password_field2" name="password" class="ls-no-style-input" value="testandosenha" >
        <a class="ls-toggle-pass" data-target="#password_field2" href="#" data-toggle-text="Ocultar">Exibir</a> |
        <a href="#" data-ls-module="modal" data-target="#changePassword">Alterar</a>
      </td>
    </tr>
    <tr>
      <td><strong>Endereço de SMTP: </strong>smtp.dominio-smtp.dominio.com</td>
    </tr>
    <tr>
      <td><strong>Porta:</strong> 587| <strong>SSL/TLS:</strong> 465</td>
    </tr>
  </tbody>
</table>

app/views/settings/edit.html.erb
<h1 class="ls-title-intro ls-ico-cog">Configurações</h1>

<%= render 'form' %>

app/views/settings/index.html.erb
<h1 class="ls-title-intro ls-ico-cog">Configurações</h1>


<% @settings.each do |setting| %>
<div class="ls-box">
<div class="row">
  <div class="col-md-12">
    <div class="ls-box">
      <p><strong>Nome do site</strong></p>
      <p class="ls-break-text"><%= setting.name %></p>
      <hr>
      <p><strong>Título</strong></p>
      <p class="ls-break-text"><%= setting.title %></p>
      <hr>
      <p><strong>Domínio</strong></p>
      <p class="ls-break-text"><%= setting.domain %></p>
      <hr>
      <p><strong>URL</strong></p>
      <p class="ls-break-text"><%= setting.url %></p>
      <hr>
      <p><strong>Email</strong></p>
      <p class="ls-break-text"><%= setting.email %></p>
      <hr>
    </div>
  </div>
</div>
</div>

<div class="ls-pagination-filter ">
<%= link_to 'Editar', edit_setting_path(setting) , class: "ls-btn-darker" %>
 </div>
<% end %>

app/views/settings/show.html.erb
<h1 class="ls-title-intro ls-ico-cog">Configurações</h1>
<%= render 'shared/notification' %>

<%= form_for(@setting, html: { class: "ls-form row" }) do |f| %>

<div class="ls-box">
<div class="row">
  <div class="col-md-12">
    <div class="ls-box">
      <p><strong>Nome do site</strong></p>
      <p class="ls-break-text"><%= @setting.name %></p>
      <hr>
      <p><strong>Título</strong></p>
      <p class="ls-break-text"><%= @setting.title %></p>
      <hr>
      <p><strong>Domínio</strong></p>
      <p class="ls-break-text"><%= @setting.domain %></p>
      <hr>
      <p><strong>URL</strong></p>
      <p class="ls-break-text"><%= @setting.url %></p>
      <hr>
      <p><strong>Email</strong></p>
      <p class="ls-break-text"><%= @setting.email %></p>
      <hr>
    </div>
  </div>
</div>
</div>

<%= link_to 'Editar', edit_setting_path(@setting), class: "ls-btn-darker" %>

<%= link_to 'Voltar', settings_path, class: "ls-btn-darker" %>

<% end %>

app/views/shared/_menu.html.erb
<aside class="ls-sidebar">
  <nav class="ls-menu">
    <ul>

      <li>
          <%= link_to 'Painel Inicial', dashboard_index_path , class: "ls-ico-dashboard" %>
      </li>

      <li class="ls-submenu">
        <a class="ls-ico-book" href=""> Livros </a>
            <ul>
                <li><a class="ls-submenu-item" href=""> Autor </a></li>
           </ul>
            <ul>
                <li><a class="ls-submenu-item" href=""> Categorias </a></li>
           </ul>
           <ul>
                <li><a class="ls-submenu-item" href=""> Emprestados </a></li>
           </ul>
           <ul>
                <li><%= link_to 'Listar Livros', books_path, class: "ls-submenu-item" %></li>
           </ul>
      </li>

      <li class="ls-submenu">
        <a class="ls-ico-users" href="">  Usuários </a>
        <ul>
           <li><a class="ls-submenu-item" href=""> Lista de Usuários </a></li>
        </ul>
      </li>

      <li class="ls-submenu">
        <a class="ls-ico-chart-bar-up" href="">  Relatórios </a>
        <ul>
           <li><a class="ls-submenu-item" href=""> Livros Cadastrados </a></li>
        </ul>
        <ul>
           <li><a class="ls-submenu-item" href=""> Livros Emprestados </a></li>
        </ul>
      </li>

      <li >
        <a class="ls-ico-user-add" href="">  Administradores </a>
       </li>


      <li class="ls-submenu">
        <a class="ls-ico-cog" href="">  Configurações </a>
        <ul>
           <li><%= link_to 'Configurações do Painel', settings_path, class: "ls-submenu-item" %></li>
        </ul>
        <ul>
           <li><%= link_to 'Dados do servidor SMTP', smtp_settings_path, class: "ls-submenu-item" %></li>
        </ul>
      </li>

    </ul>
  </nav>
</aside>

app/views/shared/_notification.html.erb
<% if flash[:notice] %>
  <div class="ls-alert-success ls-dismissable">
    <span data-ls-module="dismiss" class="ls-dismiss">&times;</span>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:error] %>
  <div class="ls-alert-danger ls-dismissable">
    <span data-ls-module="dismiss" class="ls-dismiss">&times;</span>
    <strong><%= flash[:error].fetch(:title).html_safe %></strong>
    <p><%= flash[:error].fetch(:desc).html_safe %></p>
  </div>
<% end %>